### ISSUE TITLE
Issue with REALDEBRID_MOUNT_TORRENTS_PATH on Blackhole

### ISSUE THREAD

**Issue by kennyparsons** [westsurname/scripts#10]
# Description
The error occurs when I try to bring my docker-compose stack up. I'll post my compose file below (it's the default with all the other non-blackhole related items removed).  REALDEBRID_MOUNT_TORRENTS_PATH is set to `/home/jiru443/mnt/zurg/__all__` which is the default section made by zurg, containing all torrents. The error is:
```bash
Error response from daemon: error while creating mount source path '/home/jiru443/mnt/zurg/__all__': mkdir /home/jiru443/mnt/zurg: file exists
```
This folder already exists because it's where i've mounted zurg. This is also the path I use currently with RDT Client symlinks, which has worked successfully. 

# .env (sanitized)
```env
RADARR_HOST="https://radarr"
RADARR_API_KEY="key"
RADARR_ROOT_FOLDER="/home/jiru443/mnt/infinity/movies"
REALDEBRID_ENABLED=true
REALDEBRID_HOST="https://api.real-debrid.com/rest/1.0/"
REALDEBRID_API_KEY="key"
REALDEBRID_MOUNT_TORRENTS_PATH="/home/jiru443/mnt/zurg/__all__/"
BLACKHOLE_BASE_WATCH_PATH="/home/jiru443/mnt/infinity/blackhole/watch"
BLACKHOLE_RADARR_PATH="movies"
BLACKHOLE_FAIL_IF_NOT_CACHED=true
BLACKHOLE_RD_MOUNT_REFRESH_SECONDS=60
BLACKHOLE_WAIT_FOR_TORRENT_TIMEOUT=300
BLACKHOLE_HISTORY_PAGE_SIZE=500
PYTHONUNBUFFERED=true
PUID=1000
PGID=1000
UMASK=002
#DOCKER_NETWORK="blackhole"
DOCKER_NETWORK_EXTERNAL=false
```
# docker-compose.yml
```yml
x-blackhole: &blackhole
  build:
    context: .
    dockerfile: Dockerfile.blackhole
  image: ghcr.io/westsurname/scripts/blackhole:latest
  pull_policy: always
  user: "${PUID:-}${PGID:+:${PGID}}"
  env_file:
    - .env
  restart: unless-stopped

services:
  blackhole:
    <<: *blackhole
    container_name: blackhole_service
    environment:
      - BLACKHOLE_BASE_WATCH_PATH=/${BLACKHOLE_BASE_WATCH_PATH}
    volumes:
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-${BLACKHOLE_RD_MOUNT_TORRENTS_PATH:-/dev/null}}:${REALDEBRID_MOUNT_TORRENTS_PATH:-${BLACKHOLE_RD_MOUNT_TORRENTS_PATH:-/dev/null}}
      - ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}
    profiles: [blackhole, blackhole_all, all]

networks:
  default:
    name: ${DOCKER_NETWORK:-scripts_default}
    external: ${DOCKER_NETWORK_EXTERNAL:-false}
```
