### ISSUE TITLE
"path is missing"

### ISSUE THREAD

**Issue by diegoweb** [westsurname/scripts#51]
Hey guys!

I'm having issue to set up blackhole in Portainer Stacks.

In short this is the part that matters the most (since it's a stack, it has all the other containers running together, so I'm gonna paste only blackhole part below):

```
  blackhole:
    image: ghcr.io/westsurname/scripts/blackhole:latest
    container_name: blackhole
    user: "1000:1000"
    networks:
      default:
      nginx-proxy-manager:
    volumes:
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}:${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}
      #- ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}
      - ${CONFIGS_PATH}/blackhole/logs:/app/logs
      - ${DATA_PATH}:/mnt
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - SONARR_HOST=${SONARR_HOST}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_HOST=${RADARR_HOST}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - BLACKHOLE_FAIL_IF_NOT_CACHED=${BLACKHOLE_FAIL_IF_NOT_CACHED}
      - BLACKHOLE_RD_MOUNT_REFRESH_SECONDS=${BLACKHOLE_RD_MOUNT_REFRESH_SECONDS}
      - BLACKHOLE_WAIT_FOR_TORRENT_TIMEOUT=${BLACKHOLE_WAIT_FOR_TORRENT_TIMEOUT}
      - BLACKHOLE_HISTORY_PAGE_SIZE=${BLACKHOLE_HISTORY_PAGE_SIZE}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - PLEX_HOST=${PLEX_HOST}
      - PLEX_METADATA_HOST=${PLEX_METADATA_HOST}
      - PLEX_SERVER_HOST=${PLEX_SERVER_HOST}
      - PLEX_SERVER_MACHINE_ID=${PLEX_SERVER_MACHINE_ID}
      - PLEX_SERVER_API_KEY=${PLEX_SERVER_API_KEY}
      - PLEX_SERVER_MOVIE_LIBRARY_ID=${PLEX_SERVER_MOVIE_LIBRARY_ID}
      - PLEX_SERVER_TV_SHOW_LIBRARY_ID=${PLEX_SERVER_TV_SHOW_LIBRARY_ID}
      - OVERSEERR_HOST=${OVERSEERR_HOST}
      - OVERSEERR_API_KEY=${OVERSEERR_API_KEY}
      - REALDEBRID_HOST=${REALDEBRID_HOST}
      - REALDEBRID_API_KEY=${REALDEBRID_API_KEY}
      - WATCHLIST_PLEX_PRODUCT=${WATCHLIST_PLEX_PRODUCT}
      - WATCHLIST_PLEX_VERSION=${WATCHLIST_PLEX_VERSION}
      - WATCHLIST_PLEX_CLIENT_IDENTIFIER=${WATCHLIST_PLEX_CLIENT_IDENTIFIER}
    restart: unless-stopped
    depends_on:
      - rclone
```

And these are my environment variables:
```
DATA_PATH=/home/user/plex/data
CONFIGS_PATH=/home/user/plex/configs
SERVER_DOMAIN="https://blackhole.home.mydomain.com"
PLEX_HOST="https://plex.tv/"
PLEX_METADATA_HOST="https://metadata.provider.plex.tv/"
PLEX_SERVER_HOST="https://plex:32400"
PLEX_SERVER_MACHINE_ID="DELETED"
PLEX_SERVER_API_KEY="DELETED"
PLEX_SERVER_MOVIE_LIBRARY_ID=1
PLEX_SERVER_TV_SHOW_LIBRARY_ID=2
PLEX_SERVER_PATH="DELETED"
OVERSEERR_HOST="http://overseerr:5055"
OVERSEERR_API_KEY="DELETED"
SONARR_HOST="http://sonarr:8989"
SONARR_API_KEY="DELETED"
SONARR_ROOT_FOLDER="/home/user/plex/data/media/tv"
SONARR_HOST_ANIME="http://sonarr-anime:8989"
SONARR_API_KEY_ANIME="DELETED"
SONARR_ROOT_FOLDER_ANIME="/home/user/plex/data/media/animes"
RADARR_HOST="http://radarr:7878"
RADARR_API_KEY="DELETED"
RADARR_ROOT_FOLDER="/home/user/plex/data/media/movies"
RADARR_HOST_ANIME="http://radarr-anime:7878"
RADARR_API_KEY_ANIME="DELETED"
RADARR_ROOT_FOLDER_ANIME="/home/user/plex/data/media/animes"
REALDEBRID_ENABLED=true
REALDEBRID_HOST="https://api.real-debrid.com/rest/1.0/"
REALDEBRID_API_KEY="DELETED"
REALDEBRID_MOUNT_TORRENTS_PATH="/home/user/plex/data/torrents/__all__"
WATCHLIST_PLEX_PRODUCT="Plex Media Server"
WATCHLIST_PLEX_VERSION="1.41.3.9314-a0bfb8370"
WATCHLIST_PLEX_CLIENT_IDENTIFIER="DELETED"
BLACKHOLE_BASE_WATCH_PATH="/home/user/plex/data/symlinks"
BLACKHOLE_RADARR_PATH="radarr"
BLACKHOLE_SONARR_PATH="sonarr"
BLACKHOLE_FAIL_IF_NOT_CACHED=true
BLACKHOLE_RD_MOUNT_REFRESH_SECONDS=200
BLACKHOLE_WAIT_FOR_TORRENT_TIMEOUT=60
BLACKHOLE_HISTORY_PAGE_SIZE=500
REPAIR_REPAIR_INTERVAL="10m"
REPAIR_RUN_INTERVAL="1d"
PYTHONUNBUFFERED=TRUE
PUID=1000
PGID=1000
UMASK=002
DOCKER_NETWORK="plex_default"
DOCKER_NETWORK_EXTERNAL=false
TZ=America/Sao_Paulo
```

And this is the error I'm facing in Blackhole:

> TypeError: expected str, bytes or os.PathLike object, not NoneType
>   File "/usr/local/lib/python3.9/posixpath.py", line 62, in isabs
>     s = os.fspath(s)
>     absoluteBaseWatchPath = baseWatchPath if os.path.isabs(baseWatchPath) else os.path.abspath(baseWatchPath)
>   File "/app/blackhole.py", line 81, in getPath
>     self.path_name = getPath(is_radarr, create=True)
>   File "/app/blackhole_watcher.py", line 10, in __init__
>     radarr_handler = BlackholeHandler(is_radarr=True)
>   File "/app/blackhole_watcher.py", line 22, in main
>     return future.result()
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
>     asyncio.run(main())
>   File "/app/blackhole_watcher.py", line 48, in <module>
> Traceback (most recent call last):
> Watching blackhole
> Error: Blackhole Sonarr path is missing. Please check your .env file.
> Error: Blackhole Radarr path is missing. Please check your .env file.
> Error: Blackhole base watch path is missing. Please check your .env file.
> Error: RealDebrid mount torrents path is missing. Please check your .env file.

What am I doing wrong?
Also, I haven't tried the other scripts because I think they won't be compatible with Portainer Stacks, right? They probably need to pull the repo first to have all the files locally, like this one:
```
x-blackhole: &blackhole
  build: 
    context: .
    dockerfile: Dockerfile.blackhole
  image: ghcr.io/westsurname/scripts/blackhole:latest
  pull_policy: always
  user: "${PUID:-}${PGID:+:${PGID}}"
  env_file:
    - .env
  restart: unless-stopped
```
